/*
  # Add OTP columns to rides table

  1. New Columns
    - `pickup_otp` (text, nullable) - OTP for pickup verification
    - `drop_otp` (text, nullable) - OTP for drop verification
    
  2. Security
    - These columns are accessible by drivers and customers involved in the ride
    - OTPs are cleared after successful verification
*/

-- Add OTP columns to rides table
ALTER TABLE rides 
ADD COLUMN IF NOT EXISTS pickup_otp text,
ADD COLUMN IF NOT EXISTS drop_otp text;

-- Add index for OTP lookups
CREATE INDEX IF NOT EXISTS idx_rides_pickup_otp ON rides(pickup_otp) WHERE pickup_otp IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_rides_drop_otp ON rides(drop_otp) WHERE drop_otp IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN rides.pickup_otp IS 'OTP generated by driver for customer pickup verification';
COMMENT ON COLUMN rides.drop_otp IS 'OTP generated by driver for customer drop verification';